version: '3.8'

services:
  # MariaDB Service
  mariadb:
    container_name: db
    image: mariadb:10.9
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - './mysqldata:/var/lib/mysql'

  # Adminer
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - 7777:8080

  # Laravel Application
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: 'user'
        uid: 1000
    container_name: laravel-app
    ports:
      - '8000:8000'
    volumes:
      - '/home/ubuntu/TINDERKETE/TinderketeBack:/var/www/html:rw'
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:61SeFmDJbxP1nKaqMVq1LvlsoQpB/9r0Mzmn9/BAv/w=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mariadb

# Volumes
volumes:
  mysqldata:
